version: "3.9"
services:
  some-rabbit:
    image: rabbitmq:3-management
    container_name: some-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - test-network
        
  producer-api:
    container_name: producer
    build:
      context: ./src/ProducerAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_RabbitMqSettings__Host: "some-rabbit"
      ASPNETCORE_RabbitMqSettings__QueueName: "dockerized"
    ports:
      - "90:80"
    networks:
      - test-network
    depends_on:
      - some-rabbit
      
  consumer-api:
    build:
      context: ./src/ConsumerAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_RabbitMqSettings__Host: "some-rabbit"
      ASPNETCORE_RabbitMqSettings__QueueName: "dockerized"
    ports:
      - "91-92:80"
    networks:
      - test-network
    depends_on:
      - some-rabbit
    restart: on-failure
    deploy:
      resources: 
        limits:
          cpus: '0.50'
          memory: 150M
      mode: replicated
      replicas: 2
      endpoint_mode: vip
        
networks:
  test-network:
    driver: bridge